version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable-alpine
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./uploads:/var/www/html/uploads
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/usr/src/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: "always"